changed deploy script to allow for locally generated github user page

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -1,12 +1,28 @@
 #!/bin/sh
 
+set -eu
 
 if test -z "$(git status --porcelain)"; then
-  jekyll build
-  git push
-  rsync -a --delete _site/ movb.de:www
-  rsync -a --delete _private movb.de:www
+    jekyll build
+
+    # update movb.de
+    rsync -a --delete _site/ movb.de:www
+
+    # save generated site
+    build_temp=$(mktemp -d)
+    cp -ar _site/* $build_temp
+
+    # check in generated files and push to github to update user page
+    git checkout master
+    rm -rf *
+    cp -ar $build_temp
+    git commit -m "updated site using current build in branch 'source'" .
+    git push
+
+    # go back to branch source and clear temp dir
+    git checkout source
+    rm -rf $build_temp
 else
-  echo "Git reports unclean working copy -- can't continue."
+    echo "Git reports unclean working copy -- can't continue."
 fi
 
